#ifndef SECURITY_LEVELDB_LEVELDB_H_
#define SECURITY_LEVELDB_LEVELDB_H_

#include <cstddef>
#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <utility>

#include "rust/cpp_cmp.h"
#include "rust/cpp_env.h"
#include "rust/cpp_filter.h"
#include "rust/cpp_logger.h"
#include "crubit/rust.h"
#include "absl/base/attributes.h"
#include "absl/base/thread_annotations.h"
#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "absl/strings/string_view.h"
#include "absl/synchronization/mutex.h"

namespace security::leveldb {

class Iterator;
class Snapshot;
class Options;

Options in_memory();

using Comparator = rust::Comparator;
using Env = rust::Env;
using FilterPolicy = rust::FilterPolicy;
using Logger = rust::Logger;
using SequentialFile = rust::SequentialFile;
using RandomAccessFile = rust::RandomAccessFile;
using WritableFile = rust::WritableFile;

class Options {
 public:
  Options();
  Options(const Options&) = delete;
  Options(Options&&) = default;
  Options& operator=(const Options&) = delete;
  Options& operator=(Options&&) = default;
  ~Options();

  // If true, the database will be created if it is missing.
  // Default: false
  void SetCreateIfMissing(bool val);

  // If true, an error is raised if the database already exists.
  // Default: false
  void SetErrorIfExists(bool val);

  // If true, the implementation will do aggressive checking of the
  // data it is processing and will stop early if it detects any
  // errors.  This may have unforeseen ramifications: for example, a
  // corruption of one DB entry may cause a large number of entries to
  // become unreadable or for the entire DB to become unopenable.
  // Default: false
  void SetParanoidChecks(bool val);

  // Amount of data to build up in memory (backed by an unsorted log
  // on disk) before converting to a sorted on-disk file.
  //
  // Larger values increase performance, especially during bulk loads.
  // Up to two write buffers may be held in memory at the same time,
  // so you may wish to adjust this parameter to control memory usage.
  // Also, a larger write buffer will result in a longer recovery time
  // the next time the database is opened.
  // Default: 4MB
  void SetWriteBufferSize(size_t val);

  // Number of open files that can be used by the DB.  You may need to
  // increase this if your database has a large working set (budget
  // one open file per 2MB of working set).
  // Default: 1000
  void SetMaxOpenFiles(size_t val);

  // Leveldb will write up to this amount of bytes to a file before
  // switching to a new one.
  // Most clients should leave this parameter alone.
  // Default: 2MB
  void SetMaxFileSize(size_t val);

  // Approximate capacity of block cache in bytes.
  // Default: 8MB
  void SetBlockCacheCapacityBytes(size_t val);

  // Approximate size of user data packed per block.  Note that the
  // block size specified here corresponds to uncompressed data.  The
  // actual size of the unit read from disk may be smaller if
  // compression is enabled.  This parameter can be changed dynamically.
  // Default: 4KB
  void SetBlockSize(size_t val);

  // Number of keys between restart points for delta encoding of keys.
  // This parameter can be changed dynamically.  Most clients should
  // leave this parameter alone.
  // Default: 16
  void SetBlockRestartInterval(size_t val);

  // Compression method to use (0 = NoCompression, 1 = Snappy, 2 = Zstd).
  // Default: 1 (SnappyCompression)
  void SetCompressor(uint8_t val);

  // If true, reuse the existing log file rather than creating a new one on
  // start. Default: false
  void SetReuseLogs(bool val);

  // If true, reuse the existing manifest file rather than creating a new one on
  // start. Default: false
  void SetReuseManifest(bool val);

  // Comparator used to define the order of keys in the table.
  // Default: a comparator that uses lexicographic byte-wise ordering.
  //
  // REQUIRES: The client must ensure that the comparator supplied
  // here has the same name and orders keys *exactly* the same as the
  // comparator provided to previous open calls on the same DB.
  void SetComparator(std::unique_ptr<Comparator> cmp);

  // Use the specified Env object to interact with the environment,
  // e.g. to read/write files, schedule background work, etc.
  // Default: Env::Default()
  void SetEnv(std::unique_ptr<Env> env);

  // If non-null, use the specified filter policy to reduce disk reads.
  // Many applications benefit from passing a Bloom filter policy here.
  // Default: nullptr
  void SetFilterPolicy(std::unique_ptr<FilterPolicy> filter_policy);

  // Any internal progress/error information generated by the db will
  // be written to info_log if it is non-null.
  // Default: nullptr
  void SetInfoLog(std::unique_ptr<Logger> logger);

 private:
  // Friend class DB and in_memory() helper are declared to construct Options
  // from the internal rust::Options wrapper. Making the constructor
  // private prevents external clients from directly instantiating Options
  // with internal leveldb_rs types.
  friend class DB;
  friend Options in_memory();
  explicit Options(rust::Options rs_options)
      : rs_options_(std::move(rs_options)) {}
  rust::Options rs_options_;
};

// WriteBatch holds a collection of updates to apply atomically to a DB.
//
// The updates are applied in the order in which they are added
// to the WriteBatch.  For example, the value of "key" will be "v3"
// after the following batch is written:
//
//    batch.Put("key", "v1");
//    batch.Delete("key");
//    batch.Put("key", "v2");
//    batch.Put("key", "v3");
//
class WriteBatch {
 public:
  WriteBatch();
  WriteBatch(WriteBatch&&) = default;
  WriteBatch& operator=(WriteBatch&&) = default;
  ~WriteBatch();

  // Store the mapping "key->value" in the database.
  void Put(absl::string_view key, absl::string_view value);

  // If the database contains a mapping for "key", erase it.  Else do nothing.
  void Delete(absl::string_view key);

  // Clear all updates buffered in this batch.
  void Clear();

 private:
  // Friend class DB is declared to allow the DB class to access the internal
  // rust::WriteBatch when performing atomic writes.
  friend class DB;
  rust::WriteBatch rs_batch_;
};

// A DB is a persistent ordered map from keys to values.
// A DB is safe for concurrent access from multiple threads without
// any external synchronization.
class DB {
 public:
  // Open the database with the specified "name".
  // On success, returns a pointer to a heap-allocated database.
  // On failure, returns an error status.
  static absl::StatusOr<std::unique_ptr<DB>> Open(absl::string_view name,
                                                  Options options);

  ~DB();

  // Set the database entry for "key" to "value".  Returns OK on success,
  // and a non-OK status on error.
  // If sync is true, the write will be flushed from the operating system
  // buffer cache to the storage medium before returning.
  absl::Status Put(absl::string_view key, absl::string_view value,
                   bool sync = false);

  // Remove the database entry (if any) for "key".  Returns OK on
  // success, and a non-OK status on error.  It is not an error if "key"
  // did not exist in the database.
  // If sync is true, the write will be flushed from the operating system
  // buffer cache to the storage medium before returning.
  absl::Status Delete(absl::string_view key, bool sync = false);

  // Apply the specified updates to the database.
  // Returns OK on success, non-OK on failure.
  // If sync is true, the write will be flushed from the operating system
  // buffer cache to the storage medium before returning.
  absl::Status Write(const WriteBatch& updates, bool sync = false);

  // If the database contains an entry for "key" return the corresponding value.
  // If there is no entry for "key" return a status for which
  // absl::IsNotFound() is true.
  // May return some other status on error.
  absl::StatusOr<std::string> Get(absl::string_view key);
  absl::StatusOr<std::string> GetAt(const Snapshot& snapshot,
                                    absl::string_view key);

  std::unique_ptr<Iterator> NewIterator() ABSL_ATTRIBUTE_LIFETIME_BOUND;
  std::unique_ptr<Iterator> NewIteratorAt(
      const Snapshot& snapshot ABSL_ATTRIBUTE_LIFETIME_BOUND)
      ABSL_ATTRIBUTE_LIFETIME_BOUND;
  std::unique_ptr<Snapshot> GetSnapshot() ABSL_ATTRIBUTE_LIFETIME_BOUND;

  // Compact the underlying storage for the key range [start, end].
  // In particular, deleted and overwritten versions are discarded,
  // and the data is rearranged to reduce the cost of operations
  // needed to access the data.  This operation should typically only
  // be invoked by users who understand the underlying implementation.
  //
  // start == "" is treated as a key before all keys in the database.
  // end == "" is treated as a key after all keys in the database.
  // Therefore the following call will compact the entire database:
  //    db->CompactRange("", "");
  absl::Status CompactRange(absl::string_view start, absl::string_view end);

 private:
  explicit DB(rust::DB rs_db);
  rust::DB rs_db_;
};

// An Iterator yields a sequence of key/value pairs from a source.
// Multiple threads can invoke const methods on an Iterator without
// external synchronization, but if any of the threads may call a
// non-const method, all threads accessing the same Iterator must use
// external synchronization.
class Iterator {
 public:
  ~Iterator();

  // An iterator is either positioned at a key/value pair, or not valid.
  // This method returns true if the iterator is valid.
  bool Valid() const;

  // Position at the first key in the source. The iterator is Valid()
  // after this call if the source is not empty.
  void SeekToFirst();

  // Position at the first key in the source that is at or past target.
  // The iterator is Valid() after this call if the source contains
  // an entry that comes at or past target.
  void Seek(absl::string_view target);

  // Moves to the next entry in the source. After this call, Valid() is
  // true if the iterator was not positioned at the last entry in the source.
  // REQUIRES: Valid()
  void Next();

  // Moves to the previous entry in the source. After this call, Valid() is
  // true if the iterator was not positioned at the first entry in the source.
  // REQUIRES: Valid()
  void Prev();

  // Return the key for the current entry. The underlying storage for
  // the returned key is valid only until the next modification of the iterator.
  // REQUIRES: Valid()
  absl::string_view key() const ABSL_ATTRIBUTE_LIFETIME_BOUND;

  // Return the value for the current entry. The underlying storage for
  // the returned value is valid only until the next modification of
  // the iterator.
  // REQUIRES: Valid()
  absl::string_view value() const ABSL_ATTRIBUTE_LIFETIME_BOUND;

 private:
  // Friend class DB is declared so only the DB class can construct public
  // Iterator handles from the internal rust::DBIterator wrapper, ensuring
  // client lifecycle and ownership of iterators are correctly managed by DB.
  friend class DB;
  explicit Iterator(rust::DBIterator rs_iter);

  rust::DBIterator rs_iter_;
  std::optional<std::string> current_key_;
  std::optional<std::string> current_value_;
  void RefreshCache();
};

// Abstract handle to particular state of a DB.
class Snapshot {
 public:
  ~Snapshot();

 private:
  // Friend class DB is declared so only the DB class can construct public
  // Snapshot handles from the internal rust::Snapshot wrapper, ensuring
  // client lifecycle and ownership of snapshots are correctly managed by DB.
  friend class DB;
  explicit Snapshot(rust::Snapshot rs_snapshot);
  rust::Snapshot rs_snapshot_;
};

}  // namespace security::leveldb

#endif  // SECURITY_LEVELDB_LEVELDB_H_
