#ifndef SECURITY_JSON_SERDE_JSON_SERDE_JSON_IGNORE_COMMENTS_H_
#define SECURITY_JSON_SERDE_JSON_SERDE_JSON_IGNORE_COMMENTS_H_

#include "crubit/rust.h"  // IWYU pragma: export

#endif  // SECURITY_JSON_SERDE_JSON_SERDE_JSON_IGNORE_COMMENTS_H_
