#ifndef SECURITY_JSON_SERDE_JSON_SERDE_JSON_NUMBERS_AS_STRINGS_H_
#define SECURITY_JSON_SERDE_JSON_SERDE_JSON_NUMBERS_AS_STRINGS_H_

#include "crubit/rust.h"  // IWYU pragma: export

#endif  // SECURITY_JSON_SERDE_JSON_SERDE_JSON_NUMBERS_AS_STRINGS_H_
