// Crubit does not support generic type parameters, so we need to implement
// BufferedZipFile and FsZipFile manually.

use crate::{write::CompressionMethod, ResultVecU8};
use cc_std::std::string;
use rust_vec_u8::VecU8;
use std::fmt::{Debug, Formatter};
use std::fs::File;
use std::io::{Cursor, Error, ErrorKind, Read};
use std::vec::Vec;
use zip::read::ZipFile as WrappedZipFile;
use zip::CompressionMethod as ZipCrateCompressionMethod;

#[derive(Default)]
pub struct BufferedZipFile<'a> {
    /// file is never None except for the default value, which is only
    /// used by Crubit to generate movable types.
    /// In C++, whenever a method of *ZipFile is called, the file must be
    /// checked to be not None first.
    file: Option<WrappedZipFile<'a, Cursor<Vec<u8>>>>,
}

impl<'a> Debug for BufferedZipFile<'a> {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("BufferedZipFile")
            .field("file", &if self.file.is_some() { "Some(BufferedZipFile)" } else { "None" })
            .finish()
    }
}

impl<'a> BufferedZipFile<'a> {
    /// Creates a new BufferedZipFile.
    /// This function won't be generated by Crubit and is only called from rust.
    /// (b/259749095)
    pub fn new(file: WrappedZipFile<'a, Cursor<Vec<u8>>>) -> Self {
        Self { file: Some(file) }
    }

    /// Returns whether the zip file is none (due to being default-constructed
    /// or moved-from).
    pub fn is_none(&self) -> bool {
        self.file.is_none()
    }

    /// Returns the name of the file.
    /// The result only is valid if `is_none()` returns false.
    pub fn get_file_name(&self) -> string {
        get_file_name_impl(&self.file)
    }

    /// Returns whether the entry is a file.
    /// The result only is valid if `is_none()` returns false.
    pub fn is_file(&self) -> bool {
        is_file_impl(&self.file)
    }

    /// Returns whether the entry is a directory.
    /// The result only is valid if `is_none()` returns false.
    pub fn is_dir(&self) -> bool {
        is_dir_impl(&self.file)
    }

    /// Returns the compression method of the file.
    /// The result only is valid if `is_none()` returns false.
    pub fn get_compression_method(&self) -> CompressionMethod {
        get_compression_method_impl(&self.file)
    }

    /// Returns the data of the file.
    /// The result only is valid if `is_none()` returns false.
    pub fn get_file_data(&mut self) -> ResultVecU8 {
        get_file_data_impl(&mut self.file)
    }
}

impl<'a> Read for BufferedZipFile<'a> {
    fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
        match self.file.as_mut() {
            Some(file) => file.read(buf),
            None => Err(Error::new(ErrorKind::InvalidInput, "ZipFile is not available")),
        }
    }
}

#[derive(Default)]
pub struct FsZipFile<'a> {
    /// file is never None except for the default value, which is only
    /// used by Crubit to generate movable types.
    /// In C++, whenever a method of *ZipFile is called, the file must be
    /// checked to be not None first.
    file: Option<WrappedZipFile<'a, File>>,
}

impl<'a> Debug for FsZipFile<'a> {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("FsZipFile")
            .field("file", &if self.file.is_some() { "Some(FsZipFile)" } else { "None" })
            .finish()
    }
}

impl<'a> FsZipFile<'a> {
    /// Creates a new FsZipFile.
    /// This function won't be generated by Crubit and is only called from rust.
    /// (b/259749095)
    pub fn new(file: WrappedZipFile<'a, File>) -> Self {
        Self { file: Some(file) }
    }

    /// Returns whether the zip file is none (due to being default-constructed
    /// or moved-from).
    pub fn is_none(&self) -> bool {
        self.file.is_none()
    }

    /// Returns the name of the file.
    /// The result only is valid if `is_none()` returns false.
    pub fn get_file_name(&self) -> string {
        get_file_name_impl(&self.file)
    }

    /// Returns whether the entry is a file.
    /// The result only is valid if `is_none()` returns false.
    pub fn is_file(&self) -> bool {
        is_file_impl(&self.file)
    }

    /// Returns whether the entry is a directory.
    /// The result only is valid if `is_none()` returns false.
    pub fn is_dir(&self) -> bool {
        is_dir_impl(&self.file)
    }

    /// Returns the compression method of the file.
    /// The result only is valid if `is_none()` returns false.
    pub fn get_compression_method(&self) -> CompressionMethod {
        get_compression_method_impl(&self.file)
    }

    /// Returns the data of the file.
    /// The result only is valid if `is_none()` returns false.
    pub fn get_file_data(&mut self) -> ResultVecU8 {
        get_file_data_impl(&mut self.file)
    }
}

impl<'a> Read for FsZipFile<'a> {
    fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
        match self.file.as_mut() {
            Some(file) => file.read(buf),
            None => Err(Error::new(ErrorKind::InvalidInput, "ZipFile is not available")),
        }
    }
}

fn get_file_name_impl<'a, R: Read>(file: &Option<WrappedZipFile<'a, R>>) -> string {
    match file.as_ref() {
        Some(file) => string::from(file.name()),
        None => string::from(""),
    }
}

fn is_file_impl<'a, R: Read>(file: &Option<WrappedZipFile<'a, R>>) -> bool {
    match file.as_ref() {
        Some(file) => file.is_file(),
        None => false,
    }
}

fn is_dir_impl<'a, R: Read>(file: &Option<WrappedZipFile<'a, R>>) -> bool {
    match file.as_ref() {
        Some(file) => file.is_dir(),
        None => false,
    }
}

fn get_compression_method_impl<'a, R: Read>(
    file: &Option<WrappedZipFile<'a, R>>,
) -> CompressionMethod {
    match file.as_ref() {
        Some(file) => match file.compression() {
            ZipCrateCompressionMethod::Stored => CompressionMethod::Stored,
            ZipCrateCompressionMethod::Deflated => CompressionMethod::Deflated,
            ZipCrateCompressionMethod::Bzip2 => CompressionMethod::Bzip2,
            ZipCrateCompressionMethod::Zstd => CompressionMethod::Zstd,
            ZipCrateCompressionMethod::Lzma => CompressionMethod::Lzma,
            ZipCrateCompressionMethod::Xz => CompressionMethod::Xz,
            _ => CompressionMethod::Unsupported,
        },
        None => CompressionMethod::Unsupported,
    }
}

fn get_file_data_impl<'a, R: Read>(file: &mut Option<WrappedZipFile<'a, R>>) -> ResultVecU8 {
    let result: anyhow::Result<VecU8> = match file.as_mut() {
        Some(file) => {
            let mut buffer = Vec::new();
            match file.read_to_end(&mut buffer) {
                Ok(_) => Ok(buffer.into()),
                Err(e) => Err(e.into()),
            }
        }
        None => Ok(VecU8::default()),
    };
    result.into()
}
