use crate::types::{OptionString, VecU8};
use crate::value::Value;
use exif::{Context, Tag as KamadakTag};
use std::fmt;

/// A tag of a TIFF/Exif field.
///
/// Some well-known tags are provided as associated constants of
/// this type.  The constant names follow the Exif specification
/// but not the Rust naming conventions.
///
/// A non-predefined tag can also be specified
/// by the context and the number as in `Tag(Context::Tiff, 0x100)`.
//
// This is not an enum to keep safety and API stability, while
// supporting unknown tag numbers.  This comment is based on the
// behavior of Rust 1.12.
// Storing unknown values in a repr(u16) enum is unsafe.  The compiler
// assumes that there is no undefined discriminant even with a C-like
// enum, so the exhaustiveness check of a match expression will break.
// Storing unknown values in a special variant such as Unknown(u16)
// tends to break backward compatibility.  When Tag::VariantFoo is
// defined in a new version of the library, the old codes using
// Tag::Unknown(Foo's tag number) will break.
//
// Use of constants is restricted in patterns.  As of Rust 1.12,
// PartialEq and Eq need to be _automatically derived_ for Tag to
// emulate structural equivalency.
// <https://github.com/rust-lang/rfcs/pull/1445>
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(transparent)]
pub struct Tag(KamadakTag);

impl Default for Tag {
    fn default() -> Self {
        Self(KamadakTag::Acceleration)
    }
}

impl Tag {
    /// Returns the context of the tag.
    ///
    /// # Examples
    /// ```
    /// use exif::{Context, Tag};
    /// assert_eq!(Tag::XResolution().context(), Context::Tiff);
    /// assert_eq!(Tag::DateTimeOriginal().context(), Context::Exif);
    /// ```
    pub fn context(self) -> Context {
        self.0.context()
    }

    /// Returns the tag number.
    ///
    /// # Examples
    /// ```
    /// use exif::Tag;
    /// assert_eq!(Tag::XResolution().number(), 0x11a);
    /// assert_eq!(Tag::DateTimeOriginal().number(), 0x9003);
    /// ```
    pub fn number(self) -> u16 {
        self.0.number()
    }

    /// Returns the description of the tag.
    pub fn description(&self) -> OptionString {
        self.0.description().map(|desc| VecU8(desc.as_bytes().to_vec()))
    }

    /// Returns the default value of the tag.  `None` is returned if
    /// it is not defined in the standard or it depends on another tag.
    pub fn default_value(&self) -> Option<Value> {
        self.0.default_value().map(|val| val.into())
    }

    /// Returns inner Tag structure.
    pub fn into_inner(&self) -> KamadakTag {
        self.0
    }

    /// Compare equivalence of two Tag objects.
    /// Implemented because Crubit does not expose `PartialEq` trait.
    pub fn equals(&self, other: &Tag) -> bool {
        self.0 == other.0
    }

    /// Returns true if the tag number is less than the other tag number.
    /// Implemented because Crubit does not expose `PartialOrd` trait.
    pub fn less_than(&self, other: &Tag) -> bool {
        self.0 < other.0
    }

    /// Create a Tag from context and u16.
    pub fn from_u16(context: Context, number: u16) -> Self {
        Self(KamadakTag(context, number))
    }
}

/// This is only for completeness and debugging as the original Tag implements Display as well.
impl fmt::Display for Tag {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl From<KamadakTag> for Tag {
    fn from(tag: KamadakTag) -> Self {
        Self(tag)
    }
}

impl From<Tag> for KamadakTag {
    fn from(tag: Tag) -> Self {
        tag.0
    }
}

/// The following macro code cannot be generated by Crubit:
/// http://cs///depot/google3/third_party/rust/kamadak_exif/v0_6/src/tag.rs;l=179-180
/// as it gives error `const of type `Tag` cannot be generated as only scalar consts are supported.`
/// We will use this macro to generate wrapper to all associated constants in Tag module.
macro_rules! export_exif_tags_from_const {
    (
        $( $name:ident ),* $(,)?
    ) => {
        impl Tag {
            /// Returns the tag with the corresponding name.
            ///
            /// # Examples:
            /// ```
            /// use exif::Tag;
            /// assert_eq!(Tag::XResolution().number(), 0x11a);
            /// assert_eq!(Tag::DateTimeOriginal().number(), 0x9003);
            /// ```
            $(
              #[allow(non_snake_case)]
              pub const fn $name() -> Self {
                Self(KamadakTag::$name)
              }
            )*
        }
    };
}

// Instead of turning these constants into enum in C++, we make them into function.
// Since we want them to have associated functions and
// C++ does not allow enums to have associated functions.
export_exif_tags_from_const!(
    Acceleration,
    ApertureValue,
    Artist,
    BitsPerSample,
    BodySerialNumber,
    BrightnessValue,
    CFAPattern,
    CameraElevationAngle,
    CameraOwnerName,
    ColorSpace,
    ComponentsConfiguration,
    CompositeImage,
    CompressedBitsPerPixel,
    Compression,
    Contrast,
    Copyright,
    CustomRendered,
    DateTime,
    DateTimeDigitized,
    DateTimeOriginal,
    DeviceSettingDescription,
    DigitalZoomRatio,
    ExifVersion,
    ExposureBiasValue,
    ExposureIndex,
    ExposureMode,
    ExposureProgram,
    ExposureTime,
    FNumber,
    FileSource,
    Flash,
    FlashEnergy,
    FlashpixVersion,
    FocalLength,
    FocalLengthIn35mmFilm,
    FocalPlaneResolutionUnit,
    FocalPlaneXResolution,
    FocalPlaneYResolution,
    GPSAltitude,
    GPSAltitudeRef,
    GPSAreaInformation,
    GPSDOP,
    GPSDateStamp,
    GPSDestBearing,
    GPSDestBearingRef,
    GPSDestDistance,
    GPSDestDistanceRef,
    GPSDestLatitude,
    GPSDestLatitudeRef,
    GPSDestLongitude,
    GPSDestLongitudeRef,
    GPSDifferential,
    GPSHPositioningError,
    GPSImgDirection,
    GPSImgDirectionRef,
    GPSLatitude,
    GPSLatitudeRef,
    GPSLongitude,
    GPSLongitudeRef,
    GPSMapDatum,
    GPSMeasureMode,
    GPSProcessingMethod,
    GPSSatellites,
    GPSSpeed,
    GPSSpeedRef,
    GPSStatus,
    GPSTimeStamp,
    GPSTrack,
    GPSTrackRef,
    GPSVersionID,
    GainControl,
    Gamma,
    Humidity,
    ISOSpeed,
    ISOSpeedLatitudeyyy,
    ISOSpeedLatitudezzz,
    ImageDescription,
    ImageLength,
    ImageUniqueID,
    ImageWidth,
    InteroperabilityIndex,
    InteroperabilityVersion,
    JPEGInterchangeFormat,
    JPEGInterchangeFormatLength,
    LensMake,
    LensModel,
    LensSerialNumber,
    LensSpecification,
    LightSource,
    Make,
    MakerNote,
    MaxApertureValue,
    MeteringMode,
    Model,
    OECF,
    OffsetTime,
    OffsetTimeDigitized,
    OffsetTimeOriginal,
    Orientation,
    PhotographicSensitivity,
    PhotometricInterpretation,
    PixelXDimension,
    PixelYDimension,
    PlanarConfiguration,
    Pressure,
    PrimaryChromaticities,
    RecommendedExposureIndex,
    ReferenceBlackWhite,
    RelatedImageFileFormat,
    RelatedImageLength,
    RelatedImageWidth,
    RelatedSoundFile,
    ResolutionUnit,
    RowsPerStrip,
    SamplesPerPixel,
    Saturation,
    SceneCaptureType,
    SceneType,
    SensingMethod,
    SensitivityType,
    Sharpness,
    ShutterSpeedValue,
    Software,
    SourceExposureTimesOfCompositeImage,
    SourceImageNumberOfCompositeImage,
    SpatialFrequencyResponse,
    SpectralSensitivity,
    StandardOutputSensitivity,
    StripByteCounts,
    StripOffsets,
    SubSecTime,
    SubSecTimeDigitized,
    SubSecTimeOriginal,
    SubjectArea,
    SubjectDistance,
    SubjectDistanceRange,
    SubjectLocation,
    Temperature,
    TileByteCounts,
    TileOffsets,
    TransferFunction,
    UserComment,
    WaterDepth,
    WhiteBalance,
    WhitePoint,
    XResolution,
    YCbCrCoefficients,
    YCbCrPositioning,
    YCbCrSubSampling,
    YResolution,
);
